import time
a = input("Greet the computer:  ")
time.sleep(1)
b = print(a)
time.sleep(1)
c = input("What is your name:  ")
time.sleep(1)
d = print("Hello " + c)
time.sleep(1)
e = print("I like your name")
time.sleep(1)
k = input("What is yoru favorite sport:  ")
l = print("What a wonderful sport to choise from")
f = input("What is your hobbie:  ")
time.sleep(1)
g = print("What a wonderful hobbie")
time.sleep(1)
h = input("What is your favorite desert:  ")
time.sleep(1)
i = print("I wish I could ever take " + h + " but I am only a computer")
time.sleep(2)
j = print("Bye")