print("Enter your name in small letters")
a = input("Enter your first word of your name:  ")
print(a.upper())
b = input("Enter your second word of your name:  ")
print(b)
c = input("Enter your third word of your name:  ")
print(c.upper())
d = input("Enter your fourth word of your name:  ")
print(d)
e = input("Enter your fifth word of your name:  ")
print(e.upper())
f = input("Enter your sixth word of your name:  ")
print(f)

