import time
a = input("Enter your name in small letters:  ")
time.sleep(1)
print("It will change your name from small letters to large letters")
print(a.upper())
time.sleep(1)
b = input("Enter your name in large letters:  ")
time.sleep(1)
print("It will change your name from large letters to small letters")
print(b.lower())
time.sleep(1)
print("Hello " + a + b)

print("Today I am going to help you add numbers")
time.sleep(1    )
c = input("Enter your first number:  ")
time.sleep(1)
d = input("Enter your second number:  ")
time.sleep(1)
e = input("Enter your third number:  ")
time.sleep(1)
f = int(c)
g = int(d)
h = int(e)
i = f + g + h
time.sleep(2)
print(i)